[package]
name = "data-guardian"
version = "0.1.0"
edition = "2021"
authors = ["Success Kingsley <hello@xosnrdev.tech>"]
description = "System service for monitoring and optimizing app data usage"
repository = "https://github.com/xosnrdev/data-guardian"
homepage = "https://github.com/xosnrdev/data-guardian?tab=readme-ov-file"
license = "MIT"

[[bin]]
name = "dg"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.3"
config = "0.15.8"
directories = "6.0.0"
flate2 = "1.0.35"
nix = { version = "0.29.0", features = ["user"] }
notify-rust = "4.11.5"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
sysinfo = "0.33.1"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time", "signal", "fs"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3.17.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = 'abort'
strip = true
debug = false
incremental = false
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
